RK_UBUNTU_HOSTNAME=rk3568-ubuntu

# rk3568-specific packages and overlays live under:
#   chips/rk3568/packages/<arch>/
#   chips/rk3568/overlay/
#   chips/rk3568/overlay-firmware/
#   chips/rk3568/overlay-debug/
#   chips/rk3568/apt-lists/
#   chips/rk3568/post-install.d/
