#!/bin/sh
#

[ -r /etc/lsb-release ] && . /etc/lsb-release

printf "\n"
printf "\033[1;34m"
cat <<'EOF'
                                                           ,----,             
                                               ,--.      ,/   .`|             
                 ,---,.                      ,--.'|    ,`   .'  :             
         ,--,  ,'  .'  \         ,--,    ,--,:  : |  ;    ;     /       ,--,  
       ,'_ /|,---.' .' |       ,'_ /| ,`--.'`|  ' :.'___,/    ,'      ,'_ /|  
  .--. |  | :|   |  |: |  .--. |  | : |   :  :  | ||    :     |  .--. |  | :  
,'_ /| :  . |:   :  :  /,'_ /| :  . | :   |   \ | :;    |.';  ;,'_ /| :  . |  
|  ' | |  . .:   |    ; |  ' | |  . . |   : '  '; |`----'  |  ||  ' | |  . .  
|  | ' |  | ||   :     \|  | ' |  | | '   ' ;.    ;    '   :  ;|  | ' |  | |  
:  | | :  ' ;|   |   . |:  | | :  ' ; |   | | \   |    |   |  ':  | | :  ' ;  
|  ; ' |  | ''   :  '; ||  ; ' |  | ' '   : |  ; .'    '   :  ||  ; ' |  | '  
:  | : ;  ; ||   |  | ; :  | : ;  ; | |   | '`--'      ;   |.' :  | : ;  ; |  
'  :  `--'   \   :   /  '  :  `--'   \'   : |          '---'   '  :  `--'   \ 
:  ,      .-./   | ,'   :  ,      .-./;   |.'                  :  ,      .-./ 
 `--`----'   `----'      `--`----'    '---'                     `--`----'     
                                                                                                                       
EOF
printf "\033[0m"

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
printf "\n"
printf "Welcome to %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
