RK_UBUNTU_HOSTNAME=rk3576-ubuntu
RK_UBUNTU_RKAIQ_DEB=/packages/rkaiq/camera_engine_rkaiq_rk3576_arm64.deb
RK_UBUNTU_GPU_DEBS="/packages/libmali/libmali-bifrost-g52-g13p0-x11-gbm_1.9-1_arm64.deb /packages/libmali/libmali-bifrost-g52-g13p0-x11-gbm-dbgsym_1.9-1_arm64.deb"

# rk3576-specific packages and overlays live under:
#   chips/rk3576/packages/<arch>/
#   chips/rk3576/overlay/
#   chips/rk3576/overlay-firmware/
#   chips/rk3576/overlay-debug/
