Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "Rockchip DRM"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Rockchip DRM"
EndSection
